CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE funcionario(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    cargo VARCHAR(50) NOT NULL,
    dataAdmissao DATE NOT NULL
    );